### ISSUE TITLE
[Feature Request] Convert values when unit system is changed.

### ISSUE THREAD

**Issue by KerimG** [MariaTheCoder/BMI-Calculator#1]
First of all, this is a really cool project! I think it stands out against many other BMI calculators out there, because it shows you how far away from a BMI category you are.

It would be cool, if the calculator could convert the units when the unit system is changed.

**Comment by MariaTheCoder** [comment]
Thank you for your feature request, but from a UX standpoint, I do not think that it is a good idea. 

If the user by mistake has selected the metric unit system rather than the imperial and already typed in height and weight measurements, the unit conversion becomes bothersome. I do not find it necessary to implement this feature.

**Comment by KerimG** [comment]
Hmmm, I understand. You're right. Please reject my pull request. Thank you for the explanation.
